# Generated by Django 4.2.7 on 2023-11-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbid',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
