# Generated by Django 4.2.7 on 2023-11-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_worker_hourly_rate_alter_worker_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0002_jobbid_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('feedback_receiver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_receiver', to='users.worker')),
                ('feedback_sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_sender', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='Jobs.job')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-id'],
                'unique_together': {('job', 'feedback_sender', 'feedback_receiver')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='workerfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workerfeedback',
            name='job',
        ),
        migrations.RemoveField(
            model_name='workerfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClientFeedback',
        ),
        migrations.DeleteModel(
            name='WorkerFeedback',
        ),
    ]
