# Generated by Django 4.2.7 on 2023-11-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0003_feedback_alter_workerfeedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
