# Generated by Django 4.2.7 on 2023-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_alter_feedback_feedback_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(default='Rawalpindi'),
        ),
    ]
